### ISSUE TITLE
CMS-63 Sprint 2 retrospective

### ISSUE THREAD

**Issue by camilavejar** [AndyChhuon/SOEN390#48]
Retrospective for Sprint 2.

Sprint 1 retro for reference: https://docs.google.com/document/d/1O1as8e0PXL8kmnoCeIrpOKIAHeVDU08osdEx_RnmDm4/edit?usp=sharing

**Comment by mark3737-tadros** [comment]
[Sprint 2 Retrospective.pdf](https://github.com/AndyChhuon/SOEN390/files/14483345/Sprint.2.Retrospective.pdf)
