### ISSUE TITLE
CMS-65 UI prototypes for Sprint #3 user stories

### ISSUE THREAD

**Issue by camilavejar** [AndyChhuon/SOEN390#50]

**Comment by mark3737-tadros** [comment]
[ui_prototype_Sprint3.pdf](https://github.com/AndyChhuon/SOEN390/files/14482972/ui_prototype_Sprint3.pdf)

**Comment by mark3737-tadros** [comment]
[ui_prototype_Sprint3.pdf](https://github.com/AndyChhuon/SOEN390/files/14482989/ui_prototype_Sprint3.pdf)
